kind: Ingress
metadata:
  name: brick-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/load-balancer-attributes: "dns_name=brick-lb-1329424039.us-east-1.elb.amazonaws.com"
spec:
  rules:
    - host: autometalabs.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: brick-service
                port:
                  number: 80