kind: Deployment
apiVersion: apps/v1
metadata:
  name: brick-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brick-app
  template:
    metadata:
      labels:
        app: brick-app
    spec:
      containers:
        - name: brick-app
          image: localhost:5000/brick-app
#          image: idanbenyair/atrium-react:latest
          # image: atrium-react:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 31001
      restartPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: brick-service
spec:
  type: NodePort
  ports:
    - port: 31001
      targetPort: 31001
      protocol: TCP
      nodePort: 31001
  selector:
    app: brick-app