kind: Deployment
apiVersion: apps/v1
metadata:
  name: brick-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brick-app
  template:
    metadata:
      labels:
        app: brick-app
    spec:
      containers:
        - name: brick-app
          image: zanylizard/brick-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        - name: brick-app-api
          image: zanylizard/brick-app-api
          imagePullPolicy: Always
          ports:
            - containerPort: 31002
      restartPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: brick-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31001
      protocol: TCP
  selector:
    app: brick-app
