kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-ebs-storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
