architecture: standalone
replicaCount: 1
auth:
  enabled: true
  rootPassword: Password123!
  username: lebrick
  password: Password123!
  database: brickbot_db
livenessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 10
resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"
persistence:
  storageClassName: "hostpath"
  enabled: true
  existingClaim: "hostpath-pvc"
securityContext:
  fsGroup: 1001
  runAsUser: 1001
# persistence:
#   storageClassName: "hostpath"
# persistence:
#   storageClassName: "aws-ebs-storage-class"